<?php

namespace Database\Seeders;

use App\Models\Area;
use App\Models\Region;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $areas = $areas = [
            ['code' => '1001', 'name' => 'ANYER', 'region_code' => '02'],
            ['code' => '1002', 'name' => 'AJIBARANG', 'region_code' => '03'],
            ['code' => '1003', 'name' => 'AMBARAWA', 'region_code' => '03'],
            ['code' => '2001', 'name' => 'BANDUNG', 'region_code' => '02'],
            ['code' => '2002', 'name' => 'BANJARNEGARA', 'region_code' => '03'],
            ['code' => '2003', 'name' => 'BANYUMAS', 'region_code' => '03'],
            ['code' => '2004', 'name' => 'BATU', 'region_code' => '04'],
            ['code' => '2005', 'name' => 'BANYUWANGI', 'region_code' => '04'],
            ['code' => '2006', 'name' => 'BEKASI', 'region_code' => '02'],
            ['code' => '2007', 'name' => 'BLITAR', 'region_code' => '04'],
            ['code' => '2008', 'name' => 'BOGOR', 'region_code' => '02'],
            ['code' => '2009', 'name' => 'BOJONEGORO', 'region_code' => '04'],
            ['code' => '2010', 'name' => 'BONDOWOSO', 'region_code' => '04'],
            ['code' => '2011', 'name' => 'BREBES', 'region_code' => '03'],
            ['code' => '2012', 'name' => 'BLORA', 'region_code' => '03'],
            ['code' => '2013', 'name' => 'BATANG', 'region_code' => '03'],
            ['code' => '2014', 'name' => 'BOYOLALI', 'region_code' => '03'],
            ['code' => '2015', 'name' => 'BINTARO', 'region_code' => '01'],
            ['code' => '2016', 'name' => 'BALARAJA', 'region_code' => '02'],
            ['code' => '2017', 'name' => 'BATAM', 'region_code' => '07'],
            ['code' => '2019', 'name' => 'BANDAR LAMPUNG', 'region_code' => '10'],
            ['code' => '2021', 'name' => 'BALI', 'region_code' => '05'],
            ['code' => '2022', 'name' => 'BANGKALAN', 'region_code' => '17'],
            ['code' => '3001', 'name' => 'CEPU', 'region_code' => '03'],
            ['code' => '3002', 'name' => 'CIANJUR', 'region_code' => '02'],
            ['code' => '3003', 'name' => 'CIBITUNG', 'region_code' => '02'],
            ['code' => '3004', 'name' => 'CIKAMPEK', 'region_code' => '02'],
            ['code' => '3005', 'name' => 'CIKANDE', 'region_code' => '02'],
            ['code' => '3006', 'name' => 'CIKUPA', 'region_code' => '02'],
            ['code' => '3007', 'name' => 'CILACAP', 'region_code' => '03'],
            ['code' => '3008', 'name' => 'CILEGON', 'region_code' => '02'],
            ['code' => '3009', 'name' => 'CIMAHI', 'region_code' => '02'],
            ['code' => '3010', 'name' => 'CIPANAS', 'region_code' => '02'],
            ['code' => '3011', 'name' => 'CIREBON', 'region_code' => '02'],
            ['code' => '3012', 'name' => 'CITEUREUP', 'region_code' => '02'],
            ['code' => '3013', 'name' => 'CIBINONG', 'region_code' => '02'],
            ['code' => '3014', 'name' => 'CISALAK', 'region_code' => '02'],
            ['code' => '3015', 'name' => 'CIKARANG', 'region_code' => '02'],
            ['code' => '3016', 'name' => 'CIAMIS', 'region_code' => '02'],
            ['code' => '3017', 'name' => 'CIAWI', 'region_code' => '02'],
            ['code' => '3018', 'name' => 'CINERE', 'region_code' => '02'],
            ['code' => '3019', 'name' => 'CILEUNGSI', 'region_code' => '02'],
            ['code' => '3021', 'name' => 'CILEDUG', 'region_code' => '01'],
            ['code' => '3022', 'name' => 'CISOKA', 'region_code' => '02'],
            ['code' => '4001', 'name' => 'DENPASAR', 'region_code' => '05'],
            ['code' => '4002', 'name' => 'DEPOK', 'region_code' => '02'],
            ['code' => '4003', 'name' => 'DEMAK', 'region_code' => '03'],
            ['code' => '7001', 'name' => 'GARUT', 'region_code' => '02'],
            ['code' => '7002', 'name' => 'GRESIK', 'region_code' => '04'],
            ['code' => '7003', 'name' => 'GUAM', 'region_code' => '71'],
            ['code' => '9001', 'name' => 'INDRAMAYU', 'region_code' => '02'],
            ['code' => '10001', 'name' => 'JAKARTA', 'region_code' => '01'],
            ['code' => '10002', 'name' => 'JAKARTA PUSAT', 'region_code' => '01'],
            ['code' => '10003', 'name' => 'JAKARTA UTARA', 'region_code' => '01'],
            ['code' => '10004', 'name' => 'JAKARTA BARAT', 'region_code' => '01'],
            ['code' => '10005', 'name' => 'JAKARTA TIMUR', 'region_code' => '01'],
            ['code' => '10006', 'name' => 'JAKARTA SELATAN', 'region_code' => '01'],
            ['code' => '10511', 'name' => 'CIBUBUR', 'region_code' => '02'],
            ['code' => '10901', 'name' => 'JATIBARANG', 'region_code' => '02'],
            ['code' => '10902', 'name' => 'JEMBER', 'region_code' => '04'],
            ['code' => '10903', 'name' => 'JEPARA', 'region_code' => '03'],
            ['code' => '10904', 'name' => 'JOMBANG', 'region_code' => '04'],
            ['code' => '11001', 'name' => 'KEDIRI', 'region_code' => '04'],
            ['code' => '11002', 'name' => 'KERAWANG', 'region_code' => '02'],
            ['code' => '11003', 'name' => 'KLATEN', 'region_code' => '03'],
            ['code' => '11004', 'name' => 'KUDUS', 'region_code' => '03'],
            ['code' => '11005', 'name' => 'KUNINGAN', 'region_code' => '02'],
            ['code' => '11006', 'name' => 'KEBUMEN', 'region_code' => '03'],
            ['code' => '11007', 'name' => 'KENDAL', 'region_code' => '03'],
            ['code' => '11008', 'name' => 'KUTOARJO', 'region_code' => '03'],
            ['code' => '11009', 'name' => 'KARANGANYAR', 'region_code' => '03'],
            ['code' => '11010', 'name' => 'KERTOSONO', 'region_code' => '04'],
            ['code' => '12001', 'name' => 'LABUAN', 'region_code' => '02'],
            ['code' => '12002', 'name' => 'LAWANG', 'region_code' => '04'],
            ['code' => '12003', 'name' => 'LOMBOK', 'region_code' => '06'],
            ['code' => '12004', 'name' => 'LASEM', 'region_code' => '03'],
            ['code' => '12005', 'name' => 'LAMONGAN', 'region_code' => '04'],
            ['code' => '12006', 'name' => 'LUMAJANG', 'region_code' => '04'],
            ['code' => '12007', 'name' => 'LOSARI', 'region_code' => '03'],
            ['code' => '13001', 'name' => 'MADIUN', 'region_code' => '04'],
            ['code' => '13002', 'name' => 'MAGELANG', 'region_code' => '03'],
            ['code' => '13003', 'name' => 'MALANG', 'region_code' => '04'],
            ['code' => '13004', 'name' => 'MERAK', 'region_code' => '02'],
            ['code' => '13005', 'name' => 'MOJOKERTO', 'region_code' => '04'],
            ['code' => '13007', 'name' => 'MALINGPING', 'region_code' => '02'],
            ['code' => '13008', 'name' => 'MAJALENGKA', 'region_code' => '02'],
            ['code' => '13009', 'name' => 'MAGETAN', 'region_code' => '04'],
            ['code' => '13010', 'name' => 'MOJOSARI', 'region_code' => '04'],
            ['code' => '13011', 'name' => 'MEDAN', 'region_code' => '13'],
            ['code' => '13012', 'name' => 'MANADO', 'region_code' => '09'],
            ['code' => '14001', 'name' => 'NGANJUK', 'region_code' => '04'],
            ['code' => '14002', 'name' => 'NGAWI', 'region_code' => '04'],
            ['code' => '14003', 'name' => 'NGORO', 'region_code' => '04'],
            ['code' => '16001', 'name' => 'PADALARANG', 'region_code' => '02'],
            ['code' => '16002', 'name' => 'PANDEGLANG', 'region_code' => '02'],
            ['code' => '16003', 'name' => 'PARE', 'region_code' => '04'],
            ['code' => '16004', 'name' => 'PASURUAN', 'region_code' => '04'],
            ['code' => '16005', 'name' => 'PATI', 'region_code' => '03'],
            ['code' => '16006', 'name' => 'PECANGAKAN', 'region_code' => '04'],
            ['code' => '16007', 'name' => 'PEKALONGAN', 'region_code' => '03'],
            ['code' => '16008', 'name' => 'PEMALANG', 'region_code' => '03'],
            ['code' => '16009', 'name' => 'PORONG', 'region_code' => '04'],
            ['code' => '16010', 'name' => 'PROBOLINGGO', 'region_code' => '04'],
            ['code' => '16011', 'name' => 'PUNCAK', 'region_code' => '02'],
            ['code' => '16012', 'name' => 'PURWAKARTA', 'region_code' => '02'],
            ['code' => '16013', 'name' => 'PURWOKERTO', 'region_code' => '03'],
            ['code' => '16014', 'name' => 'PALEMBANG', 'region_code' => '11'],
            ['code' => '16015', 'name' => 'PHNOM PENH', 'region_code' => '51'],
            ['code' => '16016', 'name' => 'PONOROGO', 'region_code' => '04'],
            ['code' => '16017', 'name' => 'PURBALINGGA', 'region_code' => '03'],
            ['code' => '16018', 'name' => 'PANGANDARAN', 'region_code' => '02'],
            ['code' => '16019', 'name' => 'PELABUHAN RATU', 'region_code' => '02'],
            ['code' => '16020', 'name' => 'PURWOREJO', 'region_code' => '03'],
            ['code' => '16021', 'name' => 'PURWODADI', 'region_code' => '03'],
            ['code' => '16022', 'name' => 'PANDAAN', 'region_code' => '04'],
            ['code' => '16023', 'name' => 'PAMULANG', 'region_code' => '01'],
            ['code' => '16024', 'name' => 'PACITAN', 'region_code' => '04'],
            ['code' => '16025', 'name' => 'PADANG', 'region_code' => '12'],
            ['code' => '16028', 'name' => 'BANJAR', 'region_code' => '02'],
            ['code' => '16029', 'name' => 'PAMEKASAN', 'region_code' => '17'],
            ['code' => '18001', 'name' => 'RANGKAS BITUNG', 'region_code' => '02'],
            ['code' => '18003', 'name' => 'REMBANG', 'region_code' => '03'],
            ['code' => '19001', 'name' => 'SALATIGA', 'region_code' => '03'],
            ['code' => '19002', 'name' => 'SEMARANG', 'region_code' => '03'],
            ['code' => '19003', 'name' => 'SERANG', 'region_code' => '02'],
            ['code' => '19004', 'name' => 'SIDOARJO', 'region_code' => '04'],
            ['code' => '19005', 'name' => 'SITUBONDO', 'region_code' => '04'],
            ['code' => '19006', 'name' => 'SLAWI', 'region_code' => '03'],
            ['code' => '19007', 'name' => 'SOLO', 'region_code' => '03'],
            ['code' => '19008', 'name' => 'SUBANG', 'region_code' => '02'],
            ['code' => '19009', 'name' => 'SUKABUMI', 'region_code' => '02'],
            ['code' => '19010', 'name' => 'SUKARAJA', 'region_code' => '03'],
            ['code' => '19011', 'name' => 'SUMEDANG', 'region_code' => '02'],
            ['code' => '19012', 'name' => 'SURABAYA', 'region_code' => '04'],
            ['code' => '19013', 'name' => 'SEPANJANG', 'region_code' => '04'],
            ['code' => '19015', 'name' => 'SECANG', 'region_code' => '03'],
            ['code' => '19016', 'name' => 'SRAGEN', 'region_code' => '03'],
            ['code' => '19017', 'name' => 'SOREANG', 'region_code' => '02'],
            ['code' => '19019', 'name' => 'SERPONG', 'region_code' => '02'],
            ['code' => '19020', 'name' => 'SUKOHARJO', 'region_code' => '03'],
            ['code' => '19021', 'name' => 'SUMENEP', 'region_code' => '17'],
            ['code' => '19022', 'name' => 'SAMPANG', 'region_code' => '17'],
            ['code' => '19023', 'name' => 'SOKARAJA', 'region_code' => '03'],
            ['code' => '20001', 'name' => 'TANGERANG', 'region_code' => '02'],
            ['code' => '20002', 'name' => 'TASIKMALAYA', 'region_code' => '02'],
            ['code' => '20003', 'name' => 'TEGAL', 'region_code' => '03'],
            ['code' => '20004', 'name' => 'TEMANGGUNG', 'region_code' => '03'],
            ['code' => '20005', 'name' => 'TULUNG AGUNG', 'region_code' => '04'],
            ['code' => '20006', 'name' => 'TUBAN', 'region_code' => '04'],
            ['code' => '20007', 'name' => 'TAWANGMANGU', 'region_code' => '03'],
            ['code' => '20008', 'name' => 'TRENGGALEK', 'region_code' => '04'],
            ['code' => '20010', 'name' => 'TIGARAKSA', 'region_code' => '02'],
            ['code' => '20011', 'name' => 'TANJUNG LESUNG', 'region_code' => '02'],
            ['code' => '21001', 'name' => 'UNGARAN', 'region_code' => '03'],
            ['code' => '23001', 'name' => 'WONOSOBO', 'region_code' => '03'],
            ['code' => '23002', 'name' => 'WONOSARI', 'region_code' => '03'],
            ['code' => '23003', 'name' => 'WONOGIRI', 'region_code' => '03'],
            ['code' => '23004', 'name' => 'WELERI', 'region_code' => '03'],
            ['code' => '25001', 'name' => 'YOGYAKARTA', 'region_code' => '03'],
            ['code' => '99999', 'name' => 'OVERSEAS', 'region_code' => '99'],
        ];
        foreach ($areas as $area) {
            // Find the region UUID based on the region code
            $region = Region::where('ShortChar01', $area['region_code'])->first();
            // Create the area entry with the associated region_uuid
            Area::create([
                'name' => $area['name'],
                'code' => $area['code'],
                'region_uuid' => $region ? $region->uuid : null, // Link region UUID if found,
                'created_by' => 'System',
                'updated_by' => 'System'
            ]);
        }
    }
}
